### ISSUE TITLE
Add multifile and translation support to the SPHSTLReader

### ISSUE THREAD

**Issue by greole** [greole/partikler#2]
The Reader should be able read several stl files with optional translation and rotation vector/matrix. One create a new reader model, called SPHSTLMultiReader where file expects a list of files to read

        READER:
         Wall:
            model: SPHSTLMultiReader
            file: ../example/cube.stl
            offsets: (0,0,0)
            type: fixed_wall
         Base:
           model: SPHSTLMultiReader
           file: ../example/cube.stl
           offsets: (0,0,0)
           type: material

Each body should be particularies individually to reduce computation costs.

**Comment by greole** [comment]
```

         - BOUNDARY:
                model: GenerateBoundaryParticles
                name: Cube
                file: ../example/cube.stl
                dx: 2.0
                writeout: 10
                iterations: 100
 
          - BOUNDARY:
                model: GenerateBoundaryParticles
                name: Tetrahedron
                file: ../example/Tetrahedron.stl
                dx: 1.0
                writeout: 10
                iterations: 100
                translate: [40.0, 10.0, -10.0]
```
