### ISSUE TITLE
Implement a H5Part writer

### ISSUE THREAD

**Issue by greole** [greole/partikler#5]
Currently only a crude supersph writer is availible. Hence a proper export model including an H5Part  writer should be implemented. Exporting should be done in the `POST` section of the main timeGraph.
```
-EXPORT:
    model: superSPH
    path: export/path/goes/here
    fields: empty list for all fields
```

**Comment by greole** [comment]
Additionally to an `EXPORT` model a way to set boundary and fields values is needed. Several approaches are possible:
1. Boundary conditions are generated in the `PRE` phase of the timeGraph and are referenced by the corresponding transport equations.
2. Boundary conditions are a transport  equation type model, which are called during the main loop.

In any case the following syntax should be used:

```
- BOUNDARY:
     model: fixedValue
     field:  T
     value:  500
     boundary: name of the boundary
```
